@startuml

skinparam ranksep 55
skinparam defaultTextAlignment center
'skinparam nodesep 20
skinparam shadowing false
'skinparam linetype ortho

actor user

component "Datasafe-Migration-Silent 1.0.0\n\n\n" as UBER {
  rectangle "Read/write/list file\n(SimpleDatasafeService)\nSimpleDatasafeServiceWithMigration" as proxy
  component "(0_6_1_SimpleDatasafeService) shaded datasafe 0_6_1.jar" as reader
  component "(1_0_0 SimpleDatasafeService) shaded datasafe 1.0.0.jar" as datasafe
  reader -[hidden]down-> datasafe
}

database "S3 \nbucket" as bucket
database "RDBMS/Mongo/Redis\nfor\nshedlock\nDistributed lock" as lock

user --> proxy : 1. Read file
proxy <-- bucket : 2. Read version
proxy -left-> lock : 3. Old version? Obtain migration lock
proxy --> reader : 4a. Read old version
proxy --> datasafe : 4b. New version? \n Delegate call
reader --> datasafe : 5. Write stream (old -> new)
proxy -left-> lock : 6. Release lock
proxy --> bucket : 7. Write new\nversion\nidentifier

reader <-- bucket
datasafe <--> bucket
bucket -[hidden]left-> UBER
@enduml
